package cn.mybatis.pojo;

public class Spring {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring.userId
     *
     * @mbg.generated Fri Apr 01 09:38:15 CST 2022
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring.username
     *
     * @mbg.generated Fri Apr 01 09:38:15 CST 2022
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring.password
     *
     * @mbg.generated Fri Apr 01 09:38:15 CST 2022
     */
    private String password;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring.userId
     *
     * @return the value of spring.userId
     *
     * @mbg.generated Fri Apr 01 09:38:15 CST 2022
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring.userId
     *
     * @param userid the value for spring.userId
     *
     * @mbg.generated Fri Apr 01 09:38:15 CST 2022
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring.username
     *
     * @return the value of spring.username
     *
     * @mbg.generated Fri Apr 01 09:38:15 CST 2022
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring.username
     *
     * @param username the value for spring.username
     *
     * @mbg.generated Fri Apr 01 09:38:15 CST 2022
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring.password
     *
     * @return the value of spring.password
     *
     * @mbg.generated Fri Apr 01 09:38:15 CST 2022
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring.password
     *
     * @param password the value for spring.password
     *
     * @mbg.generated Fri Apr 01 09:38:15 CST 2022
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }
}