# 开发环境配置
server:
  port: 8080

# Spring配置
spring:
  # 数据源配置
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo
    username: debian-sys-maint
    password: GJOvP46O5lTsgqLA
    hikari:
      max-lifetime: 60000
  application:
    name: order-service

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

mybatis:
  configuration:
    map-underscore-to-camel-case: true

