server:
  port: 80
spring:
  web:
    loginurl: http://localhost/
  auto:
    openurl: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/production
    username: root
    password: 123456
  thymeleaf:
    cache: false