server:
  port: 80
#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/production
#    username: root
#    password: 123456
#    type: com.zaxxer.hikari.HikariDataSource
#    hikari:
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      jdbc-url: jdbc:mysql://localhost:3306/production
#      username: root
#      password: 123456
#      minimum-idle: 5
#      idle-timeout: 300000
#      max-lifetime: 1200000
#      auto-commit: true
#      connection-test-query: select 1
spring:
  thymeleaf:
    cache: false