server:
  port: 80
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/info?characterEncoding=utf8&useSSL=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: neko.fastboot.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.commons.JakartaCommonsLoggingImpl

logging:
  pattern:
#    console: "%clr(%d{HH:mm:ss} [%t]) %highlight(%-5level) %logger{36}.%M - %msg%n"
#    %M 显示方法名
#    console: "%clr(%d{HH:mm:ss.SSS} [%t]) %highlight(%-5level) %cyan(%logger{36}) - %M - %msg%n"
    console: "%clr(%d{mm:ss.S} [%t]) %highlight(%-5level) %cyan(%logger{36})\t - %msg%n"