server:
  port: 80

# Spring配置
spring:
  application:
    name: watchdog
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      discovery:
        ephemeral: false
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order/**